name: Build

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    container: node:18-buster
    services:
      postgres:
        image: postgres/postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci
