name: Postgres

services:
  postgres:
    image: postgres/postgres
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
    ports:
      - 5432:5432

