name: Postgres

runs:
  using: "composite"

  steps:
    - name: Connect to PostgreSQL
      # Runs a script that creates a PostgreSQL table, populates
      # the table with data, and then retrieves the data.
      run: node client.ts
      # Environment variable used by the `client.js` script to create
      # a new PostgreSQL client.
      env:
        # The hostname used to communicate with the PostgreSQL service container
        DB_HOST: postgres
        # The default PostgreSQL port
        DB_PORT: 5432