name: monorepo-job-verify

runs:
  using: "composite"

  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Build
      uses: ./.github/actions/build
      with:
        package: ${{ github.workflow }}
