name: monorepo-job-verify

inputs:
  node-version:
    description: "The Node version."
    required: true

runs:
  using: "composite"

  steps:
    - name: Setup
      uses: ./.github/actions/setup
      with:
        node-version: ${{ inputs.node-version }}

    - name: Check
      uses: ./.github/actions/check
      with:
        package: ${{ github.workflow }}

    - name: Test
      uses: ./.github/actions/test
      with:
        package: ${{ github.workflow }}

    - name: Build
      uses: ./.github/actions/build
      with:
        package: ${{ github.workflow }}
