name: monorepo-publish-npm

inputs:
  package:
    description: "The package folder name."
    required: true
  segment:
    description: "The version segment to increment: major, minor, patch, or prerelease."
    required: true
  preId:
    description: 'Appended to the prerelease segment. (default: "")'

runs:
  using: "composite"

  steps:
    - name: Determine Tag
      id: tag
      shell: bash
      run: |
        if [[ ${{ inputs.segment }} == pre* ]]; then
          echo "tag=next" >> $GITHUB_OUTPUT
        else
          echo "tag=latest" >> $GITHUB_OUTPUT
        fi
    - name: Test123
      id: test123
      shell: bash
      run: |
        echo "test123"
