// todo: outside of src/ for now, vite build is placing d.ts in the incorrect location otherwise
// todo: remove vite from this package!
export * from "./src/types"
export { assembler } from "./src/assembler"
export * from "./src/dataTypes"
export * from "./src/relationships"
export * from "./src/util/camelCaseToPascalCase"
export * from "./src/util/camelCaseToStartCase"
export * from "./src/util/getEndpoint"
export * from "./src/util/getSchemaKey"
export * from "./src/util/pascalCaseToCamelCase"
export * from "./src/util/pascalCaseToKebabCase"
export * from "./src/util/pluralize"
export * from "./src/util/singularize"
export * from "./src/util/uuidv4"
