import { Hatchify as HatchifyNode, buildExportWrapper } from "@hatchifyjs/node"
import type {
  HatchifyOptions,
  ModelFunctionsCollection,
  PartialSchema,
} from "@hatchifyjs/node"

import { buildMiddlewareForModel } from "./middleware/koa.js"
import type { MiddlewareFunctionsKoa } from "./middleware/koa.js"

/**
 * Hatchify can be imported from the `@hatchifyjs/koa` package
 *
 * This class provides the entry point into the Hatchify library. To use Hatchify with your project
 * you will create an instance of this class passing it your Model definitions along with (optional) settings.
 *
 * @see {@link constructor}
 *
 * In order to use Hatchify with Koa or Express you should look at the Middleware exports below
 * @see {@link MiddlewareFunctionsKoa.all}
 *
 */
export class Hatchify extends HatchifyNode {
  constructor(
    schemas: Record<string, PartialSchema>,
    options: HatchifyOptions = {},
  ) {
    super(schemas, options)
  }

  /**
   * The `middleware` export is one of the primary tools provided by Hatchify for working
   * with your Models in custom routes.
   *
   * From the `middleware` export you can target one of your Models by name which will
   * give you further access to a number of named functions
   *
   * For more information about the underlying per-model functions:
   * @see {@link MiddlewareFunctionsKoa}
   *
   * @returns {ModelFunctionsCollection<MiddlewareFunctionsKoa>}
   * @category General Use
   */
  get middleware(): ModelFunctionsCollection<MiddlewareFunctionsKoa> {
    return buildExportWrapper<MiddlewareFunctionsKoa>(
      this,
      buildMiddlewareForModel,
    )
  }
}

export { errorHandlerMiddleware } from "./middleware/koa.js"

/**
 * `hatchifyKoa` Creates middleware functions from provided schemas
 * @param schemas An object with partial schemas
 * @param options Customization options like URL prefix and database options
 * @returns {Hatchify} A Hatchify object with the middleware functions and other autogenerated objects
 */
export function hatchifyKoa(
  schemas: Record<string, PartialSchema>,
  options: HatchifyOptions = {},
): Hatchify {
  return new Hatchify(schemas, options)
}
