name: "@hatchifyjs/crypto"

on:
  push:
  workflow_dispatch:
    inputs:
      segment:
        description: "The version segment to increment: major, minor, patch, or prerelease."
        required: true
      preId:
        description: 'Appended to the prerelease segment. (default: "")'

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify
        uses: ./.github/actions/job-verify
        with:
          node-version: ${{ matrix.node-version }}

  publish:
    if: github.event_name == 'workflow_dispatch'
    needs: verify

    concurrency:
      group: "publish"

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish
        uses: ./.github/actions/job-publish
        with:
          directory: crypto
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ github.token }}
          segment: ${{ github.event.inputs.segment }}
          preId: ${{ github.event.inputs.preId }}
