name: "@hatchifyjs/express"

on:
  push:
  workflow_dispatch:
    inputs:
      segment:
        description: "The version segment to increment: major, minor, patch, or prerelease."
        required: true
      preId:
        description: 'Appended to the prerelease segment. (default: "")'

jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify
        uses: ./.github/actions/job-verify
        with:
          node-version: ${{ matrix.node-version }}

  publish:
    if: github.event_name == 'workflow_dispatch'
    needs: verify

    concurrency:
      group: "publish"

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: ./.github/actions/job-publish
        with:
          directory: express
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ github.token }}
          segment: ${{ github.event.inputs.segment }}
          preId: ${{ github.event.inputs.preId }}
