name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build nx packages
        run: npx nx run-many -t build
      - name: Run Playwright tests for Koa/SQLite
        run: npm run e2e --frontend=react --backend=koa --database=sqlite://localhost/:memory
      - name: Run Playwright tests for Koa/Postgres
        run: npm run e2e --frontend=react --backend=koa --database=postgres://postgres:password@localhost:5432/postgres
      - name: Run Playwright tests for Express/SQLite
        run: npm run e2e --frontend=react --backend=express --database=sqlite://localhost/:memory
      - name: Run Playwright tests for Express/Postgres
        run: npm run e2e --frontend=react --backend=express ---database=postgres://postgres:password@localhost:5432/postgres
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
