name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build nx packages
        run: npx nx run-many -t build
      - name: Run Playwright tests for Koa
        run: npm run e2e --backend=koa --database=sqlite --frontend=react
      - name: Run Playwright tests for Express
        run: npm run e2e --backend=express --database=sqlite --frontend=react
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
