name: publish-all
on:
  push:
    branches: [main]
jobs:
  publish-all:
    if: ${{!contains(github.event.head_commit.message, 'skip-publish')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          safe_output: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Get changed packages
        id: changed-packages
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          TOUCHED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        run: npm run get-changed-packages
      - name: Publish crypto
        if: ${{ steps.changed-packages.outputs.crypto == 'publish' }}
        uses: ./.github/workflows/crypto
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish core
        if: ${{ steps.changed-packages.outputs.core == 'publish' }}
        uses: ./.github/workflows/core
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish node
        if: ${{ steps.changed-packages.outputs.node == 'publish' }}
        uses: ./.github/workflows/node
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish express
        if: ${{ steps.changed-packages.outputs.express == 'publish' }}
        uses: ./.github/workflows/express
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish koa
        if: ${{ steps.changed-packages.outputs.koa == 'publish' }}
        uses: ./.github/workflows/koa
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish rest-client
        if: ${{ steps.changed-packages.outputs.rest-client == 'publish' }}
        uses: ./.github/workflows/rest-client
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish rest-client-jsonapi
        if: ${{ steps.changed-packages.outputs.rest-client-jsonapi == 'publish' }}
        uses: ./.github/workflows/rest-client-jsonapi
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish react-rest
        if: ${{ steps.changed-packages.outputs.react-rest == 'publish' }}
        uses: ./.github/workflows/react-rest
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish react-ui
        if: ${{ steps.changed-packages.outputs.react-ui == 'publish' }}
        uses: ./.github/workflows/react-ui
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish react-jsonapi
        if: ${{ steps.changed-packages.outputs.react-jsonapi == 'publish' }}
        uses: ./.github/workflows/react-jsonapi
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish design-mui
        if: ${{ steps.changed-packages.outputs.design-mui == 'publish' }}
        uses: ./.github/workflows/design-mui
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish react
        if: ${{ steps.changed-packages.outputs.react == 'publish' }}
        uses: ./.github/workflows/react
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
      - name: Publish create
        if: ${{ steps.changed-packages.outputs.create == 'publish' }}
        uses: ./.github/workflows/create
        with:
          segment: ${{ steps.changed-packages.outputs.segment }}
